services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboardplayersteams
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: npm run start
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/dashboardplayersteams
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
