import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Link from "next/link";
import { LayoutDashboard, User, Users } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="main-header">
          <Link href="/">FutLovers</Link>
        </header>
        <div className="main-content">
          <div className="main-navbar">
            <div className="nav-item">
              <Link href={"/"}>
                <LayoutDashboard
                  className="nav-icon"
                  style={{ color: "white" }}
                />
              </Link>
            </div>

            <div className="nav-item">
              <Link href={"/jogadores"}>
                <User className="nav-icon" style={{ color: "white" }} />
              </Link>
            </div>
            <div className="nav-item">
              <Link href={"/times"}>
                <Users className="nav-icon" style={{ color: "white" }} />
              </Link>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
